package io.github.abdurazaaqmohammed.utils;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.junit.Test;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Verifies the smali generated by OverlayInjectorUtil is well-formed:
 * register counts on every invoke match the callee signature slots,
 * all v-registers fit in .locals, all branch labels resolve, and every
 * invoke with a non-void return is followed by move-result.
 *
 * This is a regression test for the VerifyError crash on animated borders
 * ("Rejecting invocation, expected 3 argument registers, method signature has 4").
 */
public class OverlaySmaliAuditTest {

    private static final String CLS = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity;";
    private static final String URL = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpUrl;";
    private static final String URLVIEW = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpUrlView;";
    private static final String NOSHOW = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpNoShow;";
    private static final String BLINK = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpBlink;";
    private static final String DISMISS = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpDismiss;";
    private static final String RGB = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpRgb;";
    private static final String TICK = "Lcom/abdurazaagmohammed/AntiSplit/main/MainActivity$mpRgbTick;";

    @Test
    public void regularDialogAnimatedBorder() {
        OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
        o.title = "T";
        o.message = "M";
        o.positive = "OK";
        o.positiveUrl = "https://example.com";
        o.cancelable = false;
        o.dontShowAgain = true;
        o.bgEnabled = true;
        o.bgColor1 = 0xFF112233;
        o.bgGradient = true;
        o.bgColor2 = 0xFF445566;
        o.cornerRadiusDp = 16f;
        o.borderWidthDp = 0f;
        o.borderColor = 0xFFFFFFFF;
        o.animBorder = true;
        o.animColorA = 0xFF0000FF;
        o.animColorB = 0xFFFF0000;
        o.animSpeedMs = 300;
        String smali = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, URL, null, NOSHOW, BLINK, DISMISS, new HashMap<String, String>(), null);
        auditMethod(smali, "regularDialogAnimatedBorder");
        assertFalse(smali, smali.contains(".catch"));
    }

    @Test
    public void regularDialogRainbowBorder() {
        OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
        o.title = "T";
        o.message = "M";
        o.positive = "OK";
        o.bgEnabled = true;
        o.bgColor1 = 0xFF112233;
        o.cornerRadiusDp = 16f;
        o.animBorder = true;
        o.rainbowAnim = true;
        o.animSpeedMs = 200;
        String smali = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, null, null, null, BLINK, null, new HashMap<String, String>(), null);
        auditMethod(smali, "regularDialogRainbowBorder");
        assertTrue(smali, smali.contains("0xffff0000"));
        assertTrue(smali, smali.contains("0xff00ff00"));
        assertTrue(smali, smali.contains("0xff0000ff"));
    }

    @Test
    public void regularDialogWithFontAndImage() {
        OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
        o.title = "T";
        o.message = "M";
        o.positive = "OK";
        o.negative = "No";
        o.neutral = "Later";
        o.imageBase64 = "aGk=";
        o.bgEnabled = true;
        o.bgColor1 = 0xFF112233;
        o.cornerRadiusDp = 8f;
        o.borderWidthDp = 2f;
        o.borderColor = 0xFF000000;
        o.dlgFont = "serif";
        o.titleColor = 0xFFFF0000;
        o.msgColor = 0xFF00FF00;
        o.btnColor = 0xFF0000FF;
        o.html = true;
        String smali = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, null, null, null, null, null, new HashMap<String, String>(), null);
        auditMethod(smali, "regularDialogWithFontAndImage");
        assertFalse(smali, smali.contains("createFromFile"));
        assertFalse(smali, smali.contains(".catch"));
    }

    @Test
    public void regularDialogWithFontFileUsesAsset() throws Exception {
        File font = File.createTempFile("testfont", ".ttf");
        try {
            FileOutputStream fos = new FileOutputStream(font);
            fos.write(new byte[]{0, 1, 0, 0, 0, 10});
            fos.close();
            OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
            o.title = "T";
            o.message = "M";
            o.positive = "OK";
            o.dlgFontPath = font.getAbsolutePath();
            Map<String, byte[]> bytes = OverlayInjectorUtil.collectFontAssets(o);
            assertTrue("font bytes collected", bytes.containsKey(font.getAbsolutePath()));
            Map<String, String> assets = new LinkedHashMap<>();
            assets.put(font.getAbsolutePath(), "mpfont_0.ttf");
            String smali = OverlayInjectorUtil.dialogHelperSmali(
                    CLS, o, null, null, null, null, null, assets, null);
            auditMethod(smali, "regularDialogWithFontFileUsesAsset");
            assertTrue(smali, smali.contains("createFromAsset"));
            assertTrue(smali, smali.contains("mpfont_0.ttf"));
            assertFalse(smali, smali.contains("createFromFile"));
        } finally {
            font.delete();
        }
    }

    @Test
    public void advancedDialogEverything() {
        OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
        o.advanced = true;
        o.cancelable = true;
        o.dontShowAgain = true;
        o.bgEnabled = true;
        o.bgColor1 = 0xFF000000;
        o.cornerRadiusDp = 12f;
        o.animBorder = true;
        o.animColorA = 0xFF00FF00;
        o.animColorB = 0xFFFFFF00;
        o.rainbowAnim = true;
        o.animSpeedMs = 500;
        o.dlgFont = "monospace";
        o.widgets = new ArrayList<>();
        OverlayInjectorUtil.AdvWidget text = new OverlayInjectorUtil.AdvWidget();
        text.kind = "text";
        text.text = "<b>Hello</b>";
        text.textSizeSp = 18f;
        text.textColor = 0xFFFF0000;
        text.fontStyle = 3;
        text.leftDp = 8;
        text.topDp = 8;
        o.widgets.add(text);
        OverlayInjectorUtil.AdvWidget plain = new OverlayInjectorUtil.AdvWidget();
        plain.kind = "text";
        plain.fontStyle = 1;
        plain.leftDp = 4;
        plain.topDp = 60;
        o.widgets.add(plain);
        OverlayInjectorUtil.AdvWidget btn = new OverlayInjectorUtil.AdvWidget();
        btn.kind = "button";
        btn.text = "Visit";
        btn.textSizeSp = 14f;
        btn.textColor = 0xFFFFFFFF;
        btn.btnBg = 0xFF2196F3;
        btn.btnBg2 = 0xFF0D47A1;
        btn.btnCornerRadiusDp = 12f;
        btn.btnBorderWidthDp = 2f;
        btn.btnBorderColor = 0xFFFFFFFF;
        btn.btnPaddingDp = 8;
        btn.btnAnim = true;
        btn.url = "https://example.com";
        btn.leftDp = 16;
        btn.topDp = 100;
        o.widgets.add(btn);
        OverlayInjectorUtil.AdvWidget dismiss = new OverlayInjectorUtil.AdvWidget();
        dismiss.kind = "button";
        dismiss.text = "Close";
        dismiss.leftDp = 16;
        dismiss.topDp = 160;
        o.widgets.add(dismiss);
        OverlayInjectorUtil.AdvWidget img = new OverlayInjectorUtil.AdvWidget();
        img.kind = "image";
        img.imageB64 = "aGk=";
        img.leftDp = 0;
        img.topDp = 200;
        o.widgets.add(img);
        String smali = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, URL, URLVIEW, NOSHOW, BLINK, DISMISS, new HashMap<String, String>(), null);
        auditMethod(smali, "advancedDialogEverything");
        assertFalse(smali, smali.contains("fill-array-data"));
        assertFalse(smali, smali.contains("createFromFile"));
        assertFalse(smali, smali.contains("create(Ljava/lang/String;)"));
    }

    @Test
    public void waveRgbBorder() {
        OverlayInjectorUtil.DialogOptions o = new OverlayInjectorUtil.DialogOptions();
        o.title = "T";
        o.message = "M";
        o.positive = "OK";
        o.bgEnabled = true;
        o.bgColor1 = 0xFF101010;
        o.cornerRadiusDp = 14f;
        o.animBorder = true;
        o.rainbowAnim = true;
        o.animSpeedMs = 300;
        o.advanced = true;
        o.widgets = new ArrayList<>();
        OverlayInjectorUtil.AdvWidget btn = new OverlayInjectorUtil.AdvWidget();
        btn.kind = "button";
        btn.text = "Go";
        btn.textSizeSp = 14f;
        btn.btnBg = 0xFF222222;
        btn.btnCornerRadiusDp = 10f;
        btn.btnAnim = true;
        btn.url = "https://example.com";
        btn.leftDp = 16;
        btn.topDp = 40;
        o.widgets.add(btn);
        String smali = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, null, URLVIEW, null, null, DISMISS, new HashMap<String, String>(), RGB);
        auditMethod(smali, "waveRgbBorderDialog");
        assertTrue(smali, smali.contains("$mpRgb;"));
        assertTrue(smali, smali.contains("-><init>(IFF)V"));
        assertTrue(smali, smali.contains("$mpUrlView;"));
        assertTrue(smali, smali.contains("rainbow:Z"));
        auditMethod(OverlayInjectorUtil.waveRgbSmali(RGB, TICK), "waveRgbClass");
        assertTrue(OverlayInjectorUtil.waveRgbSmali(RGB, TICK).contains(":mp_rgb_two"));
        assertTrue(OverlayInjectorUtil.waveRgbSmali(RGB, TICK).contains(":mp_rgb_grad"));
        auditMethod(OverlayInjectorUtil.waveTickSmali(TICK, RGB), "waveTickClass");
        auditMethod(OverlayInjectorUtil.urlViewListenerSmali(URLVIEW), "urlViewListener");
        o.rainbowAnim = false;
        o.animColorA = 0xFF123456;
        o.animColorB = 0xFF654321;
        String smali2 = OverlayInjectorUtil.dialogHelperSmali(
                CLS, o, null, URLVIEW, null, null, DISMISS, new HashMap<String, String>(), RGB);
        auditMethod(smali2, "waveTwoColorBorderDialog");
        assertTrue(smali2, smali2.contains("0xff123456"));
        assertTrue(smali2, smali2.contains("0xff654321"));
    }

    @Test
    public void rainbowColorsSane() {
        int[] c = OverlayInjectorUtil.rainbowColors();
        assertTrue(c.length == 12);
        assertTrue(Integer.toHexString(c[0]), c[0] == 0xFFFF0000);
        assertTrue(Integer.toHexString(c[4]), c[4] == 0xFF00FF00);
        assertTrue(Integer.toHexString(c[8]), c[8] == 0xFF0000FF);
    }

    @Test
    public void toastAndListeners() {
        OverlayInjectorUtil.ToastOptions t = new OverlayInjectorUtil.ToastOptions();
        t.message = "hi";
        t.longDuration = true;
        t.gravity = 17;
        t.xOffset = 5;
        t.yOffset = 10;
        auditMethod(OverlayInjectorUtil.toastHelperSmali(t), "toast");
        auditMethod(OverlayInjectorUtil.urlListenerSmali(URL), "urlListener");
        auditMethod(OverlayInjectorUtil.noshowListenerSmali(NOSHOW), "noshowListener");
        auditMethod(OverlayInjectorUtil.dismissSmali(DISMISS), "dismissListener");
        auditMethod(OverlayInjectorUtil.blinkSmali(BLINK), "blinkListener");
    }

    // ---------- audit engine ----------

    private static final Pattern METHOD_LINE =
            Pattern.compile("^\\.method\\s.*?(<init>|\\w+)\\(([^)]*)\\)(\\S+)\\s*$");
    private static final Pattern INVOKE =
            Pattern.compile("^\\s*invoke-(\\S+)\\s+\\{([^}]*)\\},\\s*(\\S+)->(\\S+)\\(([^)]*)\\)(\\S+)\\s*$");
    private static final Pattern LABEL_DEF = Pattern.compile("^\\s+:([A-Za-z0-9_$]+)\\s*$");
    private static final Pattern LABEL_REF = Pattern.compile("(?:[:,\\{]\\s*|^\\s*goto(?:/[0-9a-f]+)?\\s+):([A-Za-z0-9_$]+)");

    private static void auditMethod(String smali, String name) {
        assertTrue(name + ": empty smali", smali != null && smali.contains(".method"));
        String[] lines = smali.split("\n");
        int locals = -1;
        int params = 0;
        boolean inMethod = false;
        Set<String> defined = new HashSet<>();
        Map<String, Integer> defCount = new HashMap<>();
        List<String> referenced = new ArrayList<>();
        String prevInvokeRet = null;
        int prevLineNo = -1;
        int lineNo = 0;
        for (String raw : lines) {
            lineNo++;
            String line = raw.trim();
            if (line.startsWith(".method")) {
                inMethod = true;
                Matcher m = METHOD_LINE.matcher(line);
                if (m.matches()) {
                    params = countSlots(m.group(2)) + 1;
                    if (line.contains(" static ")) params--;
                }
                prevInvokeRet = null;
                continue;
            }
            if (!inMethod) continue;
            if (line.startsWith(".end method")) {
                inMethod = false;
                continue;
            }
            if (line.startsWith(".locals")) {
                locals = Integer.parseInt(line.substring(7).trim());
                continue;
            }
            Matcher ld = LABEL_DEF.matcher(raw);
            if (ld.matches()) {
                defined.add(ld.group(1));
                defCount.put(ld.group(1), defCount.getOrDefault(ld.group(1), 0) + 1);
            }
            Matcher lr = LABEL_REF.matcher(raw);
            while (lr.find()) {
                if (!raw.trim().startsWith(".array-data")
                        && !raw.trim().startsWith(".end array-data")) {
                    referenced.add(lr.group(1) + "@" + lineNo);
                }
            }
            if (line.startsWith("const-wide") || line.startsWith("const-string")
                    || line.startsWith("const/") || line.startsWith("const ")) {
                checkConstLiteral(smali, name, lineNo, line);
                prevInvokeRet = null;
            } else if (line.startsWith("move-result")) {
                if (prevInvokeRet == null) {
                    fail(name + ":" + lineNo + " move-result without invoke: " + line);
                }
                if (prevInvokeRet.equals("V")) {
                    fail(name + ":" + lineNo + " move-result after void invoke: " + line);
                }
                boolean obj = prevInvokeRet.startsWith("L") || prevInvokeRet.startsWith("[");
                if (line.startsWith("move-result-object") != obj) {
                    fail(name + ":" + lineNo + " wrong move-result kind for "
                            + prevInvokeRet + ": " + line);
                }
                prevInvokeRet = null;
            } else if (line.startsWith("invoke-")) {
                // NOTE: deliberately not failing when a previous non-void result was
                // ignored (no move-result): dropping a return value is legal Dalvik.
                Matcher m = INVOKE.matcher(raw);
                if (!m.matches()) fail(name + ":" + lineNo + " unparsable invoke: " + line);
                String kind = m.group(1);
                String regs = m.group(2).trim();
                String sig = m.group(5);
                String ret = m.group(6);
                int expected = countSlots(sig) + (kind.equals("static") ? 0 : 1);
                List<String> regList = expandRegs(regs, name, lineNo, line);
                int actual = regList.size();
                if (expected != actual) {
                    fail(name + ":" + lineNo + " invoke-" + kind + " has " + actual
                            + " regs but signature needs " + expected + ": " + line);
                }
                for (String r : regList) {
                    r = r.trim();
                    if (r.startsWith("v")) {
                        int idx = Integer.parseInt(r.substring(1));
                        if (locals >= 0 && idx >= locals) {
                            fail(name + ":" + lineNo + " register " + r
                                    + " out of range (.locals " + locals + "): " + line);
                        }
                    } else if (r.startsWith("p")) {
                        int idx = Integer.parseInt(r.substring(1));
                        if (idx >= params) {
                            fail(name + ":" + lineNo + " param " + r
                                    + " out of range (" + params + " params): " + line);
                        }
                    }
                }
                prevInvokeRet = ret;
            } else if (!line.isEmpty() && !line.startsWith(".") && !line.startsWith("#")
                    && !line.startsWith(":") && !line.startsWith("0x")) {
                // Ignoring a return value is legal; just stop tracking it.
                prevInvokeRet = null;
            }
        }
        for (Map.Entry<String, Integer> e : defCount.entrySet()) {
            if (e.getValue() > 1) fail(name + ": duplicate label :" + e.getKey());
        }
        for (String ref : referenced) {
            String label = ref.substring(0, ref.indexOf('@'));
            if (!defined.contains(label)) {
                fail(name + ": undefined label :" + label + " (referenced at line " + ref + ")");
            }
        }
    }

    private static void checkConstLiteral(String smali, String name, int lineNo, String line) {
        try {
            if (line.startsWith("const/4 ")) {
                long v = parseSmaliInt(line.substring(line.lastIndexOf(',') + 1).trim());
                if (v < -8 || v > 7) fail(name + ":" + lineNo + " const/4 out of range: " + line);
            } else if (line.startsWith("const/16 ")) {
                long v = parseSmaliInt(line.substring(line.lastIndexOf(',') + 1).trim());
                if (v < -32768 || v > 32767) fail(name + ":" + lineNo + " const/16 out of range: " + line);
            } else if (line.startsWith("const/high16 ")) {
                long v = parseSmaliInt(line.substring(line.lastIndexOf(',') + 1).trim());
                if ((v & 0xFFFFL) != 0) fail(name + ":" + lineNo + " const/high16 low bits set: " + line);
            }
        } catch (AssertionError e) {
            throw e;
        } catch (Exception e) {
            fail(name + ":" + lineNo + " unparsable const literal: " + line);
        }
    }

    private static long parseSmaliInt(String lit) {
        lit = lit.trim();
        boolean neg = lit.startsWith("-");
        if (neg) lit = lit.substring(1);
        long v;
        if (lit.startsWith("0x") || lit.startsWith("0X")) v = Long.parseLong(lit.substring(2), 16);
        else v = Long.parseLong(lit);
        return neg ? -v : v;
    }

    private static List<String> expandRegs(String regs, String name, int lineNo, String line) {
        List<String> out = new ArrayList<>();
        if (regs.isEmpty()) return out;
        Matcher range = Pattern.compile("v(\\d+) \\.\\. v(\\d+)").matcher(regs);
        if (range.find()) {
            int from = Integer.parseInt(range.group(1));
            int to = Integer.parseInt(range.group(2));
            if (to < from) fail(name + ":" + lineNo + " reversed range: " + line);
            for (int i = from; i <= to; i++) out.add("v" + i);
            return out;
        }
        for (String r : regs.split(",")) out.add(r.trim());
        return out;
    }

    private static int countSlots(String params) {
        int slots = 0;
        for (int i = 0; i < params.length(); i++) {
            char c = params.charAt(i);
            if (c == 'J' || c == 'D') {
                slots += 2;
            } else if (c == 'L') {
                slots += 1;
                while (i < params.length() && params.charAt(i) != ';') i++;
            } else if (c == '[') {
                slots += 1;
                while (i + 1 < params.length() && params.charAt(i + 1) == '[') i++;
                if (i + 1 < params.length() && params.charAt(i + 1) == 'L') {
                    i++;
                    while (i < params.length() && params.charAt(i) != ';') i++;
                } else {
                    i++;
                }
            } else {
                slots += 1;
            }
        }
        return slots;
    }
}

